apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
  - ../../base/installs/generic
  - ../../base/metadata/base
  - ../../third-party/argo/installs/namespace
  - ../../third-party/mysql/base
configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - viewer-pod-template.json
secretGenerator:
- name: mlpipeline-objects-artifact
  env: objects-artifact-secret-patch.env
  behavior: create
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
- nutanix-configuration-patch.yaml
# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
